import { Movie, User, WatchlistSettings } from '../types/Movie';

export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Morgan',
  email: 'alex@example.com',
  avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=64&h=64',
  isAdmin: true,
};

export const mockMovies: Movie[] = [
  {
    id: '1',
    title: 'The Grand Budapest Hotel',
    description: 'A quirky comedy-drama about a legendary concierge and his protégé at a famous European hotel.',
    imageUrl: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400&h=600',
    year: 2014,
    genre: 'Comedy/Drama',
    votes: 8,
    isWatched: false,
    addedBy: 'Sarah Chen',
    addedAt: new Date('2024-01-15'),
    userVote: 'up',
  },
  {
    id: '2',
    title: 'Spirited Away',
    description: 'A young girl enters a magical world ruled by spirits and must save her parents who have been transformed into pigs.',
    imageUrl: 'https://images.pexels.com/photos/7991123/pexels-photo-7991123.jpeg?auto=compress&cs=tinysrgb&w=400&h=600',
    year: 2001,
    genre: 'Animation/Fantasy',
    votes: 12,
    isWatched: false,
    addedBy: 'Mike Rodriguez',
    addedAt: new Date('2024-01-14'),
    userVote: null,
  },
  {
    id: '3',
    title: 'Mad Max: Fury Road',
    description: 'In a post-apocalyptic wasteland, Max teams up with a mysterious woman to escape a tyrannical warlord.',
    imageUrl: 'https://images.pexels.com/photos/8067845/pexels-photo-8067845.jpeg?auto=compress&cs=tinysrgb&w=400&h=600',
    year: 2015,
    genre: 'Action/Thriller',
    votes: 6,
    isWatched: false,
    addedBy: 'Jordan Kim',
    addedAt: new Date('2024-01-13'),
    userVote: 'down',
  },
  {
    id: '4',
    title: 'Parasite',
    description: 'A poor family infiltrates the lives of a wealthy household, leading to unexpected consequences.',
    imageUrl: 'https://images.pexels.com/photos/7991456/pexels-photo-7991456.jpeg?auto=compress&cs=tinysrgb&w=400&h=600',
    year: 2019,
    genre: 'Thriller/Drama',
    votes: 15,
    isWatched: false,
    addedBy: 'Emma Thompson',
    addedAt: new Date('2024-01-12'),
    userVote: 'up',
  },
];

export const watchedMovies: Movie[] = [
  {
    id: '5',
    title: 'Everything Everywhere All at Once',
    description: 'A Chinese-American woman explores parallel universes to save the multiverse.',
    imageUrl: 'https://images.pexels.com/photos/7991345/pexels-photo-7991345.jpeg?auto=compress&cs=tinysrgb&w=400&h=600',
    year: 2022,
    genre: 'Sci-Fi/Comedy',
    votes: 18,
    isWatched: true,
    addedBy: 'Alex Morgan',
    addedAt: new Date('2024-01-10'),
    watchedAt: new Date('2024-01-20'),
  },
  {
    id: '6',
    title: 'The Batman',
    description: 'Batman investigates a series of murders that lead him into Gotham\'s dark underworld.',
    imageUrl: 'https://images.pexels.com/photos/8067823/pexels-photo-8067823.jpeg?auto=compress&cs=tinysrgb&w=400&h=600',
    year: 2022,
    genre: 'Action/Crime',
    votes: 11,
    isWatched: true,
    addedBy: 'Sarah Chen',
    addedAt: new Date('2024-01-08'),
    watchedAt: new Date('2024-01-18'),
  },
];

export const watchlistSettings: WatchlistSettings = {
  id: 'watchlist-1',
  name: 'Friday Night Crew',
  description: 'Our weekly movie night picks!',
  isPublic: false,
  allowVoting: true,
  notificationsEnabled: true,
  members: [
    currentUser,
    {
      id: 'user-2',
      name: 'Sarah Chen',
      email: 'sarah@example.com',
      avatar: 'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=64&h=64',
      isAdmin: false,
    },
    {
      id: 'user-3',
      name: 'Mike Rodriguez',
      email: 'mike@example.com',
      avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=64&h=64',
      isAdmin: false,
    },
    {
      id: 'user-4',
      name: 'Jordan Kim',
      email: 'jordan@example.com',
      avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=64&h=64',
      isAdmin: false,
    },
  ],
};